name: CI/CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

  pull request:
    branches:
      - main

jobs:
  primary:
    runs-on: ubuntu-latest

    steps:
      # Son los pasos que se ejecutarán en el flujo de trabajo
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Hide this keys in the project settings in Github

      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: Deploy to AWS
        run: BUILD_DIRECTORY=build BUCKET_NAME=pablofrcontent AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws
